#!/usr/bin/env node
/*
 * Builds js/models/itoca-data.js from the ITOCA domain JSON files
 * (data/itoca/*.json), in the order of the original grid.
 *
 * Usage: node scripts/build-itoca.js
 */
'use strict';

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const ORDER = ['gov', 'purpose', 'finance', 'award', 'hr', 'network', 'advocacy', 'nrm', 'gender', 'merl'];

const domains = ORDER.map((key) => {
  const d = JSON.parse(fs.readFileSync(path.join(root, 'data', 'itoca', key + '.json'), 'utf8'));
  for (const it of d.items) {
    if (!Array.isArray(it.levels) || it.levels.length !== 4) throw new Error('4 levels expected: ' + it.id);
    for (const f of ['name', 'statement', 'action', 'verification']) {
      if (!it[f] || !it[f].fr || !it[f].en) throw new Error(f + ' missing: ' + it.id);
    }
  }
  return d;
});

const out = '/*\n * ITOCA - Integrated technical and organisational capacity assessment.\n' +
  ' * GENERATED by scripts/build-itoca.js from data/itoca/*.json - edit those files, not this one.\n' +
  ' * Source: ITOCA grid (French) generalised from an organisation-specific version,\n' +
  ' * with English translation, short titles and one suggested action per indicator.\n */\n' +
  '(function (root) {\n  \'use strict\';\n  var DOMAINS = ' + JSON.stringify(domains, null, 2).replace(/\n/g, '\n  ') + ';\n' +
  '  if (typeof module !== \'undefined\' && module.exports) module.exports = DOMAINS; else root.BarometerItocaData = DOMAINS;\n})(this);\n';

fs.writeFileSync(path.join(root, 'js', 'models', 'itoca-data.js'), out);
console.log('ITOCA: ' + domains.length + ' domains, ' + domains.reduce((n, d) => n + d.items.length, 0) + ' indicators');
