#!/usr/bin/env node
/*
 * Builds a single self-contained HTML file (dist/barometre-offline.html)
 * with every stylesheet and script inlined. The file can be copied to a USB
 * key or sent by e-mail and opened by double-click, with no internet access
 * and no other files.
 *
 * Usage: npm run build
 */
'use strict';

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const out = path.join(root, 'dist', 'barometre-offline.html');
let html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');

html = html.replace(/<link rel="stylesheet" href="([^"]+)">/g, (m, href) => {
  const css = fs.readFileSync(path.join(root, href), 'utf8');
  return '<style>\n' + css + '\n</style>';
});

html = html.replace(/<script src="([^"]+)"><\/script>/g, (m, src) => {
  // Prevent a literal "</script" inside the code from closing the tag.
  const js = fs.readFileSync(path.join(root, src), 'utf8').replace(/<\/script/gi, '<\\/script');
  return '<script>\n/* ' + src + ' */\n' + js + '\n</script>';
});

const leftovers = html.match(/<(script|link)[^>]+(src|href)="(?!#|data:)[^"]+"/g);
if (leftovers) {
  console.error('External references left in the offline build:', leftovers);
  process.exit(1);
}

const stamp = new Date().toISOString().slice(0, 10);
html = html.replace('<head>', '<head>\n  <!-- Offline build ' + stamp + ' - generated by scripts/build-offline.js; edit the source files, not this file. -->');

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, html);
console.log('Built ' + path.relative(root, out) + ' (' + Math.round(fs.statSync(out).size / 1024) + ' KB)');
